### PR TITLE
fix incorrectly-excluded radio group inputs + add button to get current page's hostname

### LINKED ISSUE #62: popup: button to get current hostname
instead of making the user figure out how to copy-paste and figure out which part of the url it means

### PR DESCRIPTION
**Pull request by hchiam**
fixes #62 and another thin

### CODE REVIEW

File: content.js [hunk 1]
```diff
@@ -548,13 +548,11 @@ ${varE}${triggerClick}${setValue}${triggerChange}`;
 
     const radioGroupNames = {};
 
-    inputElements
-      .filter((e) => e.type === "radio" && e.name)
```
Comment (hchiam) [inline content.js:552]: this was causing the index to be incorrect

File: content.js [hunk 2]
```diff
@@ -548,13 +548,11 @@ ${varE}${triggerClick}${setValue}${triggerChange}`;
...
-      .forEach((e, i) => {
-        if (!(e.name in radioGroupNames)) {
-          radioGroupNames[e.name] = i; // first index found at
-        }
-      });
+    inputElements.forEach((e, i) => {
+      if (e.type === "radio" && e.name && !(e.name in radioGroupNames)) {
```
Comment (hchiam) [inline content.js:552]: moved into this if statement

File: popup.css [hunk 3]
```diff
@@ -109,6 +109,11 @@ button:disabled,
   width: 25ch;
 }
 
+#get_hostname {
+  height: 50%;
+  margin-top: auto;
```
Comment (hchiam) [inline popup.css:114]: to align with the `#hostnames` input box

**Review by hchiam — COMMENTED** [review]
LGTM! :+1:
