### PR TITLE
Fix recording checked state of radios and checkboxes in JS record string

### LINKED ISSUE #20: bug: failing to record radios and checkboxes
content.js `action.value.replace` should be replaced with:

```js
typeof action.value === 'string' ? action.value.replace(/`/g, "\\`") : action.value;
```

### PR DESCRIPTION
**Pull request by hchiam**
fix #20

### CODE REVIEW

File: content.js [hunk 1]
```diff
@@ -168,20 +130,81 @@ async function sleep(ms){await new Promise(r=>setTimeout(r,ms||100));};`;
...
 
-    function convertActionToCode(action, recordIndex) {
+    function convertActionToCode(action, element, recordIndex) {
       let type = action.selector?.match(/\[type="(.+)"\]/) || "";
-      if (type) type = type[0];
+      if (type) {
+        type = type[0];
+      } else {
+        type = element.type;
+      }
```
Comment (hchiam) [inline content.js:139]: needed this to get the correct type for radios and checkboxes

File: content.js [hunk 2]
```diff
@@ -168,20 +130,81 @@ async function sleep(ms){await new Promise(r=>setTimeout(r,ms||100));};`;
...
       const setValue = dotValueForType(type) || "value";
       const selector = `${action.selector}${
-        action.index ? "[" + (action.index + 1) + "]" : ""
+        action.index ? ":nth-of-type(" + (action.index + 1) + ")" : ""
       }`;
-      const value = action.value.replace(/`/g, "\\`");
+      const value =
+        typeof action.value === "string"
+          ? action.value.replace(/`/g, "\\`")
+          : action.value;
```
Comment (hchiam) [inline content.js:147]: needed this to handle boolean `true` or `false` since you can't run `.replace()` on booleans, only on strings

**Review by hchiam — COMMENTED** [review]
LGTM! :+1:
